### ISSUE TITLE
about how to  Generate shadows？

### ISSUE THREAD

**Issue by zhanghongyong123456** [naoto0804/SynShadow#13]
Hello, I would like to ask. I want to match the pictures that have not been taught. Can this project be realized? Do you have any recommended open source projects to realize the generation?

**Comment by naoto0804** [comment]
Sorry, could you elaborate a bit more? I cannot imagine what "match" means in your project;
(Anyway, thank you for your interest in our repo!)

**Comment by zhanghongyong123456** [comment]
> Sorry, could you elaborate a bit more? I cannot imagine what "match" means in your project; (Anyway, thank you for your interest in our repo!)
Sorry, I didn’t make it clear
I want to Generate shadows，not  remove shadow，like this 
![image](https://user-images.githubusercontent.com/48466610/144949244-3131d9ea-8d9a-4b8f-bdc8-c419ebfbceed.png)

I want to generate corresponding shadows based on the composite image, not remove specific shadows

**Comment by naoto0804** [comment]
Thank you for the clarification! It is not applicable to your case, since we implicitly assume the occluder is out of the camera view and the scene is flat;
Here I list some papers that may be closer to your case, hope it helps!
- [Instance Shadow Detection](https://arxiv.org/abs/1911.07034)
- [Soft Shadow Network](https://openaccess.thecvf.com/content/CVPR2021/html/Sheng_SSN_Soft_Shadow_Network_for_Image_Compositing_CVPR_2021_paper.html)
- [DESOBA](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBA)

**Comment by naoto0804** [comment]
Feel free to post if you have more questions!

**Comment by zhanghongyong123456** [comment]
> I want to generate corresponding shadows based on the composite image, not remove specific shadows

Thank you very much

**Comment by naoto0804** [comment]
[My paper](https://drive.google.com/file/d/1akwQcoUa8ILWb24ZsXUKwKkccewUygW3/view) at EuroGraphics2020 might be also a way to do that!

**Comment by zhanghongyong123456** [comment]
> [My paper](https://drive.google.com/file/d/1akwQcoUa8ILWb24ZsXUKwKkccewUygW3/view) at EuroGraphics2020 might be also a way to do that!

ok，I will read and research，Is there a code（link）
