### ISSUE TITLE
version with python3.8

### ISSUE THREAD

**Issue by adriauali** [naoto0804/SynShadow#20]
Hi! I've obtained great results with some picky pics. Have you upgrade the code to be compatible with pyhon 3.8 (using to tensorflow2.x) or have you tested how difficult would be the upgrade?? thksss great work

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our work, and glad to hear that it works on your pics! Unfortunately, I haven't upgraded the code, but it should not be difficult since Python3 is mostly backward compatible, and I cannot find anything special in [doc](https://docs.python.org/3/whatsnew/3.8.html). I would appreciate it if you could send a PR for 3.8 (or more recent versions, since 3.8 will also be EOL in this year).

**Comment by naoto0804** [comment]
Closed due to inactivity, feel free to re-open the issue if you want to discuss more!
